apiVersion: v1
kind: Config
clusters:
- name: {{ cluster }}
  cluster:
    certificate-authority-data: {{ cert-authority-data }}
    server: {{ server }}
contexts:
- context:
    cluster: {{ cluster }}
    namespace: {{ default_ns }}
    user: {{ username }}
  name: {{ default_ns }}
current-context: {{ default_ns }}
users:
- name: {{ username }}
  user:
    token: {{ jwt }}
