apiVerion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ default_ns }}
  name: {{ default_ns }}-user
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
  nonResourceURLs:
  - '*'
  verbs:
  - '*'
