apiVersion: v1
kind: Namespace
metadata:
  name: external-routing
---
apiVersion: v1
kind: Service
metadata:
  name: service-ip
  namespace: external-routing
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 443
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: service-ip
  namespace: external-routing
subsets:
- addresses:
  - ip: 10.1.1.3
  ports:
  - name: app
    port: 80
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "example-issuer-prod"
  name: external-service
  namespace: external-routing
spec:
  rules:
  - host: service.example.com
    http:
      paths:
      - backend:
          serviceName: service-ip
          servicePort: 443
        path: /
  tls:
    - hosts:
        - "*.example.com"
      secretName: exmaple-secret

