apiVersion: v1
kind: ConfigMap
metadata:
  name: wan-test
  labels:
    app: wan-test
  namespace: default
data:
  wan-test.sh: |
    $!/bin/bash
    domains=(
        google.com
        tolson.dev
        reddit.com
        kubernetes.io
    )

    for host in "${domains[@]}"; do
        ping -c 1 $host
        if [[ "$?" != "0" ]]; then
            echo "Can't reach host, should curl somewhere but exit... and crash"
            exit 1
        fi
    done
