# This is a namespace stub, imagine it stored in the repo with
# the associated users and groups.
# for user in joe bob sally; do sed "s/\$user/$user/" namespace.yaml; done

##############################################################
# $user Namespace
##############################################################
---
apiVersion: v1
kind: Namespace
metadata:
  name: $user
  labels:
    group: $user
    type: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-$user
  namepace: $user
subjects:
- kind: User
  name: $user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ResouceQuota
metadata:
  name: $user-resquota
  namespace: $user
spec:
  hard:
    limits.cpu: 2
    limits.memory: 8Gi
